### ISSUE TITLE
Resolve ASF web-checker issues.

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo-website#420]
The ASF has a tool that examines the web-site and reports potential issues.  The report can be seen at [Accumulo Site Check](https://whimsy.apache.org/site/project/accumulo)

Currently there are two issues flagged.  Missing link to ASF privacy policy and links to external resources.

According to the tool, the privacy policy is expected to be 
```
\Ahttps://privacy\.apache\.org/policies/privacy-policy-public\.html\z | \Ahttps?://(?:www\.)?apache\.org/foundation/policies/privacy\.html\z
```
The reported external resources are:
```
Found 6 external resources: {"cdn.jsdelivr.net"=>2, "cdnjs.cloudflare.com"=>2, "cdn.datatables.net"=>2}
```

**Comment by ctubbsii** [comment]
I'm working on this. We can fix these for most of the website, but the website also hosts the older 1.x user manuals, which were generated by asciidoctor and have links to CDN content. We can't really fix those because they are static generated content from a previous build that we're hosting... but I don't think the tool is really checking those anyway. Fixing it in the default layout should be sufficient.

**Comment by ctubbsii** [comment]
This won't show up as fixed right away, but can check back in a couple days to see if all is green on the Whimsy dashboard again.

**Comment by ctubbsii** [comment]
Just checked again, and we're all green now.
